// Token list for the DEX.
//
// The addresses are NOT hardcoded: `deployedTokens.json` is generated by
// `npm run deploy:tokens` so the frontend always matches the running chain.
// Only presentation metadata (name/logo) lives here.

import deployedTokens from "./deployedTokens.json";

const METADATA = {
  USDC: {
    name: "USD Coin",
    logoURI: "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png",
  },
  DAI: {
    name: "Dai Stablecoin",
    logoURI: "https://assets.coingecko.com/coins/images/9956/large/4948.png",
  },
  WBTC: {
    name: "Wrapped Bitcoin",
    logoURI: "https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png",
  },
  WETH: {
    name: "Wrapped Ether",
    logoURI: "https://assets.coingecko.com/coins/images/2518/large/weth.png",
  },
  LINK: {
    name: "Chainlink",
    logoURI: "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png",
  },
  UNI: {
    name: "Uniswap",
    logoURI: "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png",
  },
};

// The contracts have no native-ETH support (no WETH wrapper in the router), so
// ETH is listed for display only - the swap/add forms disable it explicitly.
export const NATIVE_ETH_ADDRESS = "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE";

const NATIVE_ETH = {
  name: "Ether",
  symbol: "ETH",
  address: NATIVE_ETH_ADDRESS,
  decimals: 18,
  logoURI: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
  native: true,
};

export const TOKEN_LIST = [
  NATIVE_ETH,
  ...(deployedTokens ?? []).map((token) => ({
    name: METADATA[token.symbol]?.name ?? token.name,
    symbol: token.symbol,
    address: token.address,
    decimals: token.decimals ?? 18,
    logoURI: METADATA[token.symbol]?.logoURI ?? "",
    native: false,
  })),
];

/** Tokens the DEX can actually trade (everything except the ETH placeholder). */
export const TRADABLE_TOKENS = TOKEN_LIST.filter((token) => !token.native);

export const getTokenBySymbol = (symbol) =>
  TOKEN_LIST.find((token) => token.symbol.toLowerCase() === String(symbol).toLowerCase());

export const getTokenByAddress = (address) =>
  TOKEN_LIST.find((token) => token.address?.toLowerCase() === String(address).toLowerCase());

export const searchTokens = (query) => {
  if (!query) return TOKEN_LIST;
  const lower = query.toLowerCase();
  return TOKEN_LIST.filter(
    (token) =>
      token.name.toLowerCase().includes(lower) ||
      token.symbol.toLowerCase().includes(lower) ||
      token.address.toLowerCase().includes(lower)
  );
};
