/**
 * Tiny .env helper shared by the deployment / indexer scripts.
 * Keeps a single source of truth for addresses that the frontend, the indexer
 * and the Python agents all need.
 */
import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

export const PROJECT_ROOT = join(__dirname, "..");
export const ENV_PATH = join(PROJECT_ROOT, ".env");

export function readEnv() {
  const env = {};
  if (!existsSync(ENV_PATH)) return env;
  for (const line of readFileSync(ENV_PATH, "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

/**
 * Merge `updates` into .env, preserving unknown keys and comments.
 */
export function writeEnv(updates) {
  const lines = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf-8").split("\n") : [];
  const remaining = { ...updates };

  const next = lines.map((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return line;
    const eq = trimmed.indexOf("=");
    if (eq === -1) return line;
    const key = trimmed.slice(0, eq).trim();
    if (!(key in remaining)) return line;
    const value = remaining[key];
    delete remaining[key];
    return `${key}=${value}`;
  });

  if (Object.keys(remaining).length > 0) {
    if (next.length && next[next.length - 1].trim() !== "") next.push("");
    next.push("# --- generated by Scripts/deploy.js ---");
    for (const [key, value] of Object.entries(remaining)) next.push(`${key}=${value}`);
  }

  writeFileSync(ENV_PATH, next.join("\n").replace(/\n*$/, "\n"));
  return updates;
}
