import { existsSync, readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_PATH = join(__dirname, "..", "frontend", "src", "constants", "deployedTokens.json");

/**
 * Reads the token list generated by Scripts/deploy_tokens.js
 */
export function loadTokens() {
  if (!existsSync(TOKENS_PATH)) {
    throw new Error(
      `No deployed tokens found at ${TOKENS_PATH}. Run "npm run deploy:tokens" first.`
    );
  }

  const tokens = JSON.parse(readFileSync(TOKENS_PATH, "utf-8"));
  if (!Array.isArray(tokens) || tokens.length === 0) {
    throw new Error("deployedTokens.json is empty. Run \"npm run deploy:tokens\" first.");
  }
  return tokens;
}

export function tokenAddress(symbol) {
  const token = loadTokens().find((t) => t.symbol === symbol);
  if (!token) throw new Error(`Token ${symbol} not found in deployedTokens.json`);
  return token.address;
}
